-- Step 1: Add email column (nullable)
ALTER TABLE public.team_master ADD COLUMN email text NULL;

-- Step 2: Clear existing rows inserted without email
DELETE FROM public.team_master;

-- Step 3: Re-insert all members with emails
INSERT INTO public.team_master (name, email) VALUES
  ('Abantika Kahali',        'abantika.kahali@leadschool.in'),
  ('Abhishek Bhatnagar',     'abhishek.bhatnagar1@leadschool.in'),
  ('Aditi Gupta',            'aditi.gupta_c@leadschool.in'),
  ('Ajay Kashyap',           'ajay.kashyap@leadschool.in'),
  ('Akanksha Anand',         'akanksha.anand@leadschool.in'),
  ('Amol Gavasane',          'amol.gavasane@leadschool.in'),
  ('Anjutha L',              'anjutha.l@leadschool.in'),
  ('Anshu Kumar Jha',        'anshukumar.jha@leadschool.in'),
  ('Anusha Sayyed',          'anusha.sayyed@leadschool.in'),
  ('Apurva Khanduri',        'apurva.khanduri@leadschool.in'),
  ('Arzoo Chawla',           'arzoo.chawla@leadschool.in'),
  ('Asim Anwar',             'asim.anwar1@leadschool.in'),
  ('Astha Jain',             'astha.jain@leadschool.in'),
  ('Avni Agarwal',           'avni.agarwal@leadschool.in'),
  ('Ayushi Nagar',           'ayushi.nagar@leadschool.in'),
  ('Bhagya Laxmi',           'bhagya.laxmi@leadschool.in'),
  ('Bhavya Kapoor',          'bhavya.kapoor1@leadschool.in'),
  ('Chanchala Kumari',       'chanchala.kumari@leadschool.in'),
  ('Deepika Aggarwal',       'deepika.aggarwal@leadschool.in'),
  ('Dinu Sankar',            'dinu.sankar@leadschool.in'),
  ('Dipika Gohain',          'dipika.gohain@leadschool.in'),
  ('Disha Jain',             'disha.jain@leadschool.in'),
  ('Gul Afshan Baig',        'gul.baig@leadschool.in'),
  ('Gunjan Sabharwal',       'gunjan.sabharwal@leadschool.in'),
  ('Hannah Hopman',          'hannah.hopman@leadschool.in'),
  ('Ishita Ralhan',          'ishita.ralhan@leadschool.in'),
  ('Juanita Newnes',         'juanita.n@leadschool.in'),
  ('Kavita Sharma',          'kavita.sharma@leadschool.in'),
  ('Kritika Gautam',         'kritika.gautam_c@leadschool.in'),
  ('Kuldeep Sahu',           'kuldeep.sahu@leadschool.in'),
  ('Kumar Sourabh',          'kumar.sourabh@leadschool.in'),
  ('Leann D''Almeida',       'leann.dalmeida1@leadschool.in'),
  ('Madhav Vyas',            'madhav.vyas@leadschool.in'),
  ('Mahesh Gavankar',        'mahesh.gavankar@leadschool.in'),
  ('Mangesh Bhandari',       'mangesh.bhandari@leadschool.in'),
  ('Manigandan S',           'manigandan.sampath@lbpl.co'),
  ('Manish Doshi',           'manish.doshi@leadschool.in'),
  ('Mansi Pade',             'mansi.pade@leadschool.in'),
  ('Meghna Guha',            'meghna.guha@leadschool.in'),
  ('Mohit Khurana',          'mohit.khurana@leadschool.in'),
  ('Mrinanda Baruah',        'mrinanda.baruah@leadschool.in'),
  ('Mrudul Bhagat',          'mrudul.bhagat@leadschool.in'),
  ('Nancy Soreng',           'nancy.soreng@leadschool.in'),
  ('Narasimha Prasad',       'narasimha.prasad@leadschool.in'),
  ('Needa Nasir',            'needa.nasir@leadschool.in'),
  ('Nirmiti Zalpuri',        'nirmiti.zalpuri@leadschool.in'),
  ('Pankaj Mohan Tulaskar',  'pankaj.t@leadschool.in'),
  ('Panna Kumaresh Purohit', 'panna.purohit@leadschool.in'),
  ('Paromita Chakraborty',   'paromita.chakraborty@leadschool.in'),
  ('Priyanka Gunasekaran',   'priyanka.gunasekaran@leadschool.in'),
  ('Priyanka Kanavi',        'priyanka.kanavi@leadschool.in'),
  ('Rahul Goswami',          'rahul.goswami@leadschool.in'),
  ('Rajesh Acharya',         'rajesh.acharya@leadschool.in'),
  ('Ranita Ghosh',           'ranita.ghosh@leadschool.in'),
  ('Ritika Manoja',          'ritika.manoja@leadschool.in'),
  ('Ruchi Goil',             'ruchi.goil@leadschool.in'),
  ('Ruchi Mittal',           'ruchi.mittal@leadschool.in'),
  ('Sangeeta Das',           'sangeeta.d@leadschool.in'),
  ('Sanya Hariyani',         'sanya.hariyani@leadschool.in'),
  ('Seema Singh',            'seema.singh@leadschool.in'),
  ('Shikha Gogia',           'shikha.gogia@leadschool.in'),
  ('Shilpa Sharma',          'shilpa.sharma@leadschool.in'),
  ('Shirin Vij',             'shirin.vij@leadschool.in'),
  ('Shreya Anand',           'shreya.anand@leadschool.in'),
  ('Shubhra U',              'shubhra.u@leadschool.in'),
  ('Siddharth Nithyanand',   'siddharth.nithyanand@leadschool.in'),
  ('Siddharth Sonti',        'siddharth.sonti@leadschool.in'),
  ('Smita Deorah',           'smita@leadschool.in'),
  ('Somya Pandey',           'somya.pandey@leadschool.in'),
  ('Sonal Dahiyaa',          'sonal.dahiyaa@leadschool.in'),
  ('Sudeshna Dasgupta',      'sudeshna.dasgupta1@leadschool.in'),
  ('Sumit Singh Rawat',      'sumit.rawat@lbpl.co'),
  ('Tanya Gambhir',          'tanya.gambhir@leadschool.in'),
  ('Tripti Moolchandani',    'tripti.moolchandani@leadschool.in'),
  ('Vanita Makwana',         'vanita.makwana@leadschool.in'),
  ('Veena G P',              'veena.gp@leadschool.in'),
  ('Viddhi Kapoor',          'viddhi.kapoor@leadschool.in'),
  ('Vijay Kumar Singh',      'vijay.singh@leadschool.in'),
  ('Vijendra',               'vijendra.umarwal@lbpl.co'),
  ('Vikas Yadav',            'vikas.yadav@leadschool.in'),
  ('Vimal Sagar',            'vimal.sagar@leadschool.in'),
  ('Visalam Narayanan',      'visalam.narayanan@leadschool.in'),
  ('Yathish Dhavala',        'yathish.dhavala@leadschool.in');
